In [1]:
import pandas as pd
import numpy as np 

In [2]:
df = pd.read_csv('Churn_Modelling.csv')

In [3]:
df.head()

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0

In [4]:
X = df.iloc[:, 3: -1].values
y = df.iloc[:, -1].values

In [6]:
print(X)

[[619 'France' 'Female' ... 1 1 101348.88]
 [608 'Spain' 'Female' ... 0 1 112542.58]
 [502 'France' 'Female' ... 1 0 113931.57]
 ...
 [709 'France' 'Female' ... 0 1 42085.58]
 [772 'Germany' 'Male' ... 1 0 92888.52]
 [792 'France' 'Female' ... 1 0 38190.78]]


In [7]:
print(y)

[1 0 1 ... 1 1 0]


# Data Preprocess

In [9]:
# Encoding Categorical data
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
X[:, 2] = le.fit_transform(X[:, 2])

In [ ]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [1])], 
                      remainder='passthrough')
X = np.array(ct.fit_transform(X))

In [10]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(),[1])],
                       remainder='passthrough')

X = np.array(ct.fit_transform(X))

In [11]:
print(X)

[[1.0 0.0 0.0 ... 1 1 101348.88]
 [0.0 0.0 1.0 ... 0 1 112542.58]
 [1.0 0.0 0.0 ... 1 0 113931.57]
 ...
 [1.0 0.0 0.0 ... 0 1 42085.58]
 [0.0 1.0 0.0 ... 1 0 92888.52]
 [1.0 0.0 0.0 ... 1 0 38190.78]]


In [12]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2)

In [ ]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.fit_transform(X_test)

In [13]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.fit_transform(X_test)

# Build an ANN model

In [14]:
import tensorflow as tf

In [15]:
model = tf.keras.models.Sequential()

In [16]:
model.add(tf.keras.layers.Dense(units = 6, activation='relu'))
model.add(tf.keras.layers.Dense(units = 6, activation = 'relu'))
model.add(tf.keras.layers.Dense(units = 1, activation = 'sigmoid'))

In [18]:
model.compile(optimizer='adam',
              loss = 'binary_crossentropy',
             metrics=['accuracy'])

In [19]:
model.fit(X_train, y_train, batch_size = 32, epochs=100)

Epoch 1/100
250/250 [==============================] - 0s 884us/step - loss: 0.5376 - accuracy: 0.7435
Epoch 2/100
250/250 [==============================] - 0s 898us/step - loss: 0.4710 - accuracy: 0.7990
Epoch 3/100
250/250 [==============================] - 0s 925us/step - loss: 0.4510 - accuracy: 0.7999
Epoch 4/100
250/250 [==============================] - 0s 928us/step - loss: 0.4407 - accuracy: 0.8024
Epoch 5/100
250/250 [==============================] - 0s 893us/step - loss: 0.4348 - accuracy: 0.8071
Epoch 6/100
250/250 [==============================] - 0s 898us/step - loss: 0.4310 - accuracy: 0.8077
Epoch 7/100
250/250 [==============================] - 0s 945us/step - loss: 0.4282 - accuracy: 0.8087
Epoch 8/100
250/250 [==============================] - 0s 937us/step - loss: 0.4255 - accuracy: 0.8109
Epoch 9/100
250/250 [==============================] - 0s 893us/step - loss: 0.4225 - accuracy: 0.8124
Epoch 10/100
250/250 [==============================] - 0s 874us/step - l

250/250 [==============================] - 0s 903us/step - loss: 0.3329 - accuracy: 0.8641
Epoch 80/100
250/250 [==============================] - 0s 853us/step - loss: 0.3330 - accuracy: 0.8625
Epoch 81/100
250/250 [==============================] - 0s 872us/step - loss: 0.3326 - accuracy: 0.8637
Epoch 82/100
250/250 [==============================] - 0s 701us/step - loss: 0.3326 - accuracy: 0.8634
Epoch 83/100
250/250 [==============================] - 0s 755us/step - loss: 0.3325 - accuracy: 0.8636
Epoch 84/100
250/250 [==============================] - 0s 893us/step - loss: 0.3326 - accuracy: 0.8625
Epoch 85/100
250/250 [==============================] - 0s 920us/step - loss: 0.3328 - accuracy: 0.8621
Epoch 86/100
250/250 [==============================] - 0s 917us/step - loss: 0.3325 - accuracy: 0.8633
Epoch 87/100
250/250 [==============================] - 0s 926us/step - loss: 0.3327 - accuracy: 0.8645
Epoch 88/100
250/250 [==============================] - 0s 805us/step - loss:

In [24]:
from sklearn.metrics import confusion_matrix

In [ ]:
cm = confusion_matrix()

In [22]:
prediction = model.predict(X_test)

In [23]:
prediction

array([[0.02961424],
       [0.064262  ],
       [0.635076  ],
       ...,
       [0.12134597],
       [0.09968641],
       [0.11646926]], dtype=float32)